services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432 # change ports if you have other postgres instances running
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=slightlysecurepassword123 # change this if you are stupid enough to use this app in production
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  adminer: # you should probably remove this in production
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080